### ISSUE TITLE
Doesn't work in Classic theme

### ISSUE THREAD

**Issue by Rubenvanhoeyveld** [PrestaShop/ps_viewedproduct#2]
It won't register which products are viewed. I think it has something to do with a hook named 'displayProductButtons', because I can't find that hook. I tried changing this to 'displayFooterProduct'. It then would add the product ID to the cookie, but the products won't show up. I then put back the 'displayProductButtons'. Now that I had a product in cookie, it showed the products list, but now it won't add other products to the cookie anymore.

(This is at line 171 of ps_viewedproduct.php)

**Comment by Rubenvanhoeyveld** [comment]
Ok, I got it to work by changing this:
```    
public function renderWidget($hookName = null, array $configuration = [])
    {
        if ('displayProductButtons' === $hookName) {
            $this->addViewedProduct($configuration['product']['id_product']);
            return;
        }
```

to this:

```
    public function renderWidget($hookName = null, array $configuration = [])
    {
        if ('displayFooterProduct' === $hookName) {
            $this->addViewedProduct($configuration['product']['id_product']);
        }
```

Note: I changed the hookName from `displayProductButtons` to `displayFooterProduct`, because the `displayProductButtons` hook no longer exists.

So now it adds the product and without the return, it also shows the list of products.

**Comment by antoin-m** [comment]
Hi @CodingPeak,

Are you sure your module was up to date? It should be using the "displayProductAdditionalInfo" hook.

Regards,
Michel ANTOINE

**Comment by CodingPeak** [comment]
This was a new installation of PS 1.7.1.2. I also disabled, uninstalled, installed and updated the module.

Also, in the code, there's no mention of "displayProductAdditionalInfo" as far as I can see.

**Comment by antoin-m** [comment]
Oh right, my bad. It has been changed here : https://github.com/PrestaShop/ps_viewedproduct/commit/ca0f1be591cc043f8785d450947f47f769aa56d5#diff-e414f7c019ae050c0b3eb25b51b014c8L74

@aleeks if you have a minute to explain 🐼

**Comment by aleeks** [comment]
Because the module was for 1.7.0.0 and before it was displayProductButtons used.
displayProductAdditionalInfo has been introduce in 1.7.1.0, maybe that's why.
